### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by ka11i0** [Decending/E7020E_lab1#1]
1) Yes
2) Tror det är rätt :)
3) Bra
4) Yes
5) Ser bra ut
6) Bra
7) Bra
8) Bra
9) Bra
10) Nice
11) "Once you have added the 1.9v power supply you can add a new power net, and connect that to your PMW3389 component." kolla reference schematic i datascheetet för pmw. 
12) bRA
13) Ser bra ut
14) Dubbelkolla label output/input förhållandena. Och vet inte om det behövs men som i 11) kolla reference schematic i datascheetet för pmw. 
15) Bör vara rätt.
16) Ser bra ut lite osäker på AP footprinten dock, själv använde jag SOT-23W_Handsoldering.
17) Bra!

**Comment by Decending** [comment]
Jag har uppdaterat lab 1 nu, kolla gärna igenom om jag har svarat på all feedback du gav mig.
Om jag inte hör ifrån dig förrän ikväll så stänger jag denna tråden.

**Comment by ka11i0** [comment]
Det ser bra ut
